// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

using MySql.Data.MySqlClient;

namespace EM {

	public class Table {

		private String name;
		private List<Column> column =  new List<Column>();

		public Table(){}

		public Table(String name){
			this.name = name;
		}

		public void addColumn(Column column){
			this.column.Add(column);
		}

		public String getCreateTable(){
			String sql = "Create table if not exists `"+name+"` (";

			for(int i=0; i < this.column.Count; i++){
				sql += "`"+this.column[i].name+"` "+this.column[i].GetTypeColumn();
				if((i + 1) < this.column.Count)
					sql += ",";
			}

			sql += ");";
			return sql;
		}

		public void insert(List<Value> values){
			String sql = getInsert (values);
			MyConnection mc = MyConnection.GetInstance ();
			mc.Execute (sql);
		}

		public List<Result> select(){
			return this.selectFrom (this.column);
		}

		public List<Result> select(List<Column> column){
			return this.selectFrom (column);
		}

		private List<Result> selectFrom(List<Column> column){
			List<Result> resultado = new List<Result> ();
			String sql = getSelect (column);
			//Console.WriteLine (sql);
			
			MyConnection mc = MyConnection.GetInstance ();
			
			MySqlDataReader dataReader = mc.GetResult (sql);
			
			
			while (dataReader.Read()) {
				Result r = new Result();
				foreach(Column cc in column){
					Value v = new Value();
					v.setColumn(cc);
					v.setValue(cc, dataReader[cc.name]);
					//Console.WriteLine(v.getValue());
					r.addValue(v);
				}
				
				
				resultado.Add(r);
			}
			
			dataReader.Close();
			
			return resultado;
		}

		private List<Result> selectFrom(List<Column> column, String Where){
			List<Result> resultado = new List<Result> ();
			String sql = getSelect (column, Where);
			
			
			MyConnection mc = MyConnection.GetInstance ();
			
			MySqlDataReader dataReader = mc.GetResult (sql);
			
			
			while (dataReader.Read()) {
				Result r = new Result();
				foreach(Column cc in column){
					Value v = new Value();
					v.setColumn(cc);
					v.setValue(cc, dataReader[cc.name]);
					r.addValue(v);
				}
				resultado.Add(r);
			}
			
			dataReader.Close();

			mc.CloseConnection ();
			
			return resultado;
		}

		private String getSelect(List<Column> column, String Where){
			String sql = "Select ";
			for(int i=0; i < column.Count; i++){
				sql += "`"+column[i].name+"` ";
				if((i + 1) < column.Count)
					sql += ",";
			}
			
			sql += " FROM `"+this.name+"` WHERE "+Where+";";
			
			return sql;
		}

		private String getInsert(List<Value> values){
			try{
				String sql = "Insert into `"+this.name+"` (";
				String Values = "";
				for(int i=0; i < column.Count; i++){
					sql += "`"+column[i].name+"` ";
					foreach(Value vv in values){
						if(vv.getColumn().name.Equals(column[i].name)){
							Values += "'"+values[i].getValue().ToString()+"' ";
						}
					}
					if((i + 1) < column.Count){
						sql += ",";
						Values += ",";
					}
				}
				
				sql += ") VALUES ( "+Values+" );";
			
			
				return sql;
			}catch(Exception){
				
			}

			return "";
		}

		private String getSelect(List<Column> column){
			String sql = "Select ";
			for(int i=0; i < column.Count; i++){
				sql += "`"+column[i].name+"` ";
				if((i + 1) < column.Count)
					sql += ",";
			}

			sql += " FROM `"+this.name+"` WHERE 1;";

			//Console.WriteLine (sql);

			return sql;
		}



	}

	public class Column {
		public string name;

		public TypeColumn type;

		public int size;

		public String GetTypeColumn(){
			switch(type){
				case(TypeColumn.VARCHAR):
					return "VARCHAR("+this.size+")";


				default:
					return this.type.ToString();

			}
		}
	}
	
	public enum TypeColumn {
		VARCHAR,
		TEXT,
		BOOLEAN,
		LONGBLOB,
		BLOB,
		FLOAT,
		DOUBLE
	}

	public class Result {
		private List<Value> value = new List<Value> ();

		public void addValue(Value value){
			this.value.Add(value);
		}

		public List<Value> getValues(){
			return this.value;
		}
	}

	public class Value {
		private Column column;

		private String s_value;
		private float  f_value;
		private bool   b_value;
		private double d_value;


		public void setColumn(Column column){
			this.column = column;
		}

		public Column getColumn(){
			return column;
		}

		public void setValue(Column column, Object value){
			switch(column.type){
				case(TypeColumn.VARCHAR):
					this.s_value = (String) value;
				break;

				case(TypeColumn.TEXT):
					this.s_value = (String) value;
				break;

				case(TypeColumn.BOOLEAN):
					this.b_value = (bool) value;
				break;
					
				case(TypeColumn.LONGBLOB):
					this.s_value = (String) value;
				break;	

				case(TypeColumn.BLOB):
					this.s_value = (String) value;
				break;	

				case(TypeColumn.FLOAT):
					this.f_value = (float) value;
				break;	

				case(TypeColumn.DOUBLE):
					this.d_value = (double) value;
				break;	
			}
		}

		public Object getValue(){
			switch(column.type){
				case(TypeColumn.VARCHAR):
					return this.s_value;

				
				case(TypeColumn.TEXT):
					return this.s_value;

				
				case(TypeColumn.BOOLEAN):
					return this.b_value;

				
				case(TypeColumn.LONGBLOB):
					return this.s_value;

				
				case(TypeColumn.BLOB):
					return this.s_value;

				
				case(TypeColumn.FLOAT):
					return this.f_value;

				
				case(TypeColumn.DOUBLE):
					return this.d_value;

			}
			return null;
		}
	}


}

